spring.application.name=VaultIQ

# === Server ===
server.port=8080

# === MySQL (Production DB - hosted, NOT localhost) ===
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect

# === HikariCP (Connection Pool) ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# === Mail (Brevo SMTP) ===
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# === JWT ===
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# === URLs ===
vaultiq.frontend.url=${FRONTEND_URL}
vaultiq.backend.url=${BACKEND_URL}

# === Logging ===
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.file.name=logs/vaultiq.log