# === PostgreSQL Production Database ===
spring.datasource.url=jdbc:postgresql://ep-proud-dew-aioouu6f-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZiQ3THWu0YxL

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Connection Pool
spring.datasource.hikari.maximum-pool-size=5